version: '3.9'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ./entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3